@extends('include.front')
@section('content') 

 <!-- Stat main -->
      <main data-spy="scroll" data-target="#navbar-example2" data-offset="0">
        <!-- Start banner_about -->
        <section class="pt_banner_inner banner_px_image" id="Discover">
          <div class="parallax_cover">
            <img class="cover-parallax" src="{{asset('front/img/inner/privacy.jpg')}}" alt="image">
          </div>
          <div class="container">
            <div class="row">
              <div class="col-md-8 col-lg-6">
                <div class="banner_title_inner">
                  <h1 data-aos="fade-up" data-aos-delay="0">
                    Privacy-Policy
                  </h1>
                  <p data-aos="fade-up" data-aos-delay="100">
                    Our Policy.
                  </p>
                  

                </div>
              </div>

            </div>
          </div>
        </section>
        <!-- End banner_about -->

		
		
		 <!-- Start about_cc_grid -->
        <section class="about_cc_grid padding-py-12" id="About">
          <div class="container">
            
			
			<div class="Section0" style="layout-grid:18.0000pt;"><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">VISION-X PRIVACY POLICY</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><p class="MsoNormal"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-weight:bold;
font-size:10.0000pt;">This privacy policy shall be effective from 14th October, 2020. </span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-weight:bold;
font-size:10.0000pt;"><o:p></o:p></span></b></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;">We at Vision-X Crypto Currency Services Ltd (herein referred to as "Vision-X", "we", "us" or "our") respect and protect the privacy of visitors to our websites and our customers. This Privacy Policy describes our information handling practices when you access our services, which include our content on the websites located at&nbsp;</span><span><a href="https://visionxcrpto.com"><u><span class="18" style="mso-spacerun:'yes';font-family:Arial;line-height:114%;
color:rgb(0,0,255);text-decoration:underline;text-underline:single;
font-size:10.0000pt;">visionxcrypto.com</span></u></a></span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;">, or any other websites or domains, pages, features, or content we own or operate (collectively, the "Site(s)") or when you use the Vision-X mobile app, the Vision-X Card/app (as defined below), any Vision-X, Vision-X Pro, or Vision-X Custody API or third party applications relying on such an API, and related services (referred to collectively hereinafter as "Services").</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;">Please take a moment to read this Privacy Policy carefully. If you have any questions about this Policy, please submit your request via our Support Portal at&nbsp;</span><span><a href="https://visionxcrpto.com/contact-us"><u><span class="18" style="mso-spacerun:'yes';font-family:Arial;line-height:114%;
color:rgb(0,0,255);text-decoration:underline;text-underline:single;
font-size:10.0000pt;">https://visionxcrpto.com/</span></u><u><span class="18" style="mso-spacerun:'yes';font-family:Arial;line-height:114%;
color:rgb(0,0,255);text-decoration:underline;text-underline:single;
font-size:10.0000pt;">c</span></u><u><span class="18" style="mso-spacerun:'yes';font-family:Arial;line-height:114%;
color:rgb(0,0,255);text-decoration:underline;text-underline:single;
font-size:10.0000pt;">ontact-us</span></u><u><span class="18" style="mso-spacerun:'yes';font-family:Arial;line-height:114%;
color:rgb(0,0,255);text-decoration:underline;text-underline:single;
font-size:10.0000pt;">&nbsp;</span></u><u><span class="18" style="mso-spacerun:'yes';font-family:Arial;line-height:114%;
color:rgb(0,0,255);text-decoration:underline;text-underline:single;
font-size:10.0000pt;"><o:p></o:p></span></u></a></span></p><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">ACCEPTANCE OF THIS PRIVACY POLICY</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><p class="p" style="margin-top:0.0000pt;margin-bottom:18.0000pt;line-height:114%;
background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;">By accessing and using our Services, you signify acceptance to the terms of this Privacy Policy. Where we require your consent to process your personal information, we will ask for your consent to the collection, use, and disclosure of your personal information as described further below. We may provide additional "just-in-time" disclosures or information about the data processing practices of specific Services. These notices may supplement or clarify our privacy practices or may provide you with additional choices about how we process your data.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;">If you do not agree with or you are not comfortable with any aspect of this Privacy Policy, you should immediately discontinue access or use of our Services.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;"><o:p></o:p></span></p><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">CHANGES TO THIS PRIVACY POLICY</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><p class="MsoNormal"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);">We may modify this Privacy Policy from time to time which will be indicated by changing the date at the top of this page. If we make any material changes, we will notify you by email (sent to the email address specified in your account), by means of a notice on our Services prior to the change becoming effective, or as otherwise required by law. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);"><o:p></o:p></span></p><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;
background:rgb(255,255,255);mso-shading:rgb(255,255,255);">THE PERSONAL INFORMATION WE COLLECT</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;
background:rgb(255,255,255);mso-shading:rgb(255,255,255);"><o:p></o:p></span></b></h1><p class="MsoNormal"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);">Personal information is typically data that identifies an individual or relates to an identifiable individual. This includes information you provide to us, information which is collected about you automatically, and information we obtain from third parties.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);">Information you provide to us</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);"><o:p></o:p></span></b></p><p class="MsoNormal" align="justify" style="margin-bottom:18.0000pt;text-align:justify;text-justify:inter-ideograph;
background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">To create an account and access our Services, we'll ask you to provide us with some important information about yourself. This information is either required by law (e.g. to verify your identity), necessary to provide the requested services (e.g. you will need to provide your bank account number if you'd like to link that account to Vision-X), or is relevant for certain specified purposes, described in greater detail below. As we add new features and Services, you may be asked to provide additional information.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:18.0000pt;text-align:justify;text-justify:inter-ideograph;
background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">Please note that we may not be able to serve you as effectively or offer you our Services if you choose not to share certain information with us. Any information you provide to us that is not required is voluntary.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:18.0000pt;text-align:justify;text-justify:inter-ideograph;
background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">We may collect the following types of information from you:</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l4 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Personal Identification Information</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: Full name, date of birth, nationality, gender, signature, utility bills, photographs, phone number, home address, and/or email.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l4 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Formal Identification Information</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: Government issued identity document such as Passport, Driver's License, National Identity Card, State ID Card, Tax ID number, passport number, driver's license details, national identity card details, visa information, and/or any other information deemed necessary to comply with our legal obligations under financial or anti-money laundering laws.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l4 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Institutional Information</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: Employer Identification number (or comparable number issued by a government), proof of legal formation (e.g. Articles of Incorporation), personal identification information for all material beneficial owners.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l4 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Financial Information</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: Bank account information, payment card primary account number (PAN), transaction history, trading data, and/or tax identification.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l4 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Transaction Information</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: Information about the transactions you make on our Services, such as the name of the recipient, your name, the amount, and/or timestamp.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l4 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Employment Information</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: Office location, job title, and/or description of role.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l4 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Correspondence</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: Survey responses, information provided to our support team or user research team. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:0.7500pt;
mso-margin-top-alt:auto;text-align:justify;text-justify:inter-ideograph;
background:rgb(255,255,255);"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">Information we collect from you automatically </span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:0.7500pt;
mso-margin-top-alt:auto;text-align:justify;text-justify:inter-ideograph;
background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">To the extent permitted under the applicable law, we may collect certain types of information automatically, such as whenever you interact with the Sites or use the Services. This information helps us address customer support issues, improve the performance of our Sites and applications, provide you with a streamlined and personalized experience, and protect your account from fraud by detecting unauthorized access. Information collected automatically includes:</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l1 level1 lfo2;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-bidi-font-family:Arial;font-weight:bold;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;font-weight:bold;
font-size:10.0000pt;">Online Identifiers</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">: Geo location/tracking details, browser fingerprint, operating system, browser name and version, and/or personal IP addresses.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l1 level1 lfo2;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-bidi-font-family:Arial;font-weight:bold;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;font-weight:bold;
font-size:10.0000pt;">Usage Data</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">: Authentication data, security questions, click-stream data, public social networking posts, and other data collected via cookies and similar technologies. Please read our</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
color:rgb(5,15,25);font-size:10.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">Cookie Policy</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
color:rgb(5,15,25);font-size:10.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">for more information. For example, we may automatically receive and record the following information on our server logs:</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l0 level1 lfo3;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:Calibri;mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">How you came to and use the Services;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l0 level1 lfo3;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:Calibri;mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">Device type and unique device identification numbers;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l0 level1 lfo3;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:Calibri;mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">Device event information (such as crashes, system activity and hardware settings, browser type, browser language, the date and time of your request and referral URL);</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l0 level1 lfo3;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:Calibri;mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">How your device interacts with our Sites and Services, including pages accessed and links clicked;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l0 level1 lfo3;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:Calibri;mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">Broad geographic location (e.g. country or city-level location); and</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l0 level1 lfo3;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:Calibri;mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;">Other technical data collected through cookies, pixel tags and other similar technologies that uniquely identify your browser.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We may also use identifiers to recognize you when you access our Sites via an external link, such as a link appearing on a third party site. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">Information collected from third parties </span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;"><o:p></o:p></span></b></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We may </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);">obtain information about you from third party sources as required or permitted by applicable law. These sources may include: </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l3 level1 lfo4;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Public Databases, Credit Bureaus &amp; ID Verification Partners</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: We obtain information about you from public databases and ID verification partners for purposes of verifying your identity in accordance with applicable law. ID verification partners like World-Check use a combination of government records and publicly available information about you to verify your identity. Such information may include your name, address, job role, public employment profile, credit history, status on any sanctions lists maintained by public authorities, and other relevant data. We obtain such information to comply with our legal obligations, such as anti-money laundering laws. In some cases, we may process additional data about you to assess risk and ensure our Services are not used fraudulently or for other illicit activities. In such instances, processing is necessary for us to continue to perform our contractual obligations with you and others. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l3 level1 lfo4;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Blockchain Data</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: We may analyze public blockchain data to ensure parties utilizing our Services are not engaged in illegal or prohibited activity under our Terms, and to analyze transaction trends for research and development purposes.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l3 level1 lfo4;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Joint Marketing Partners &amp; Resellers</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: For example, unless prohibited by applicable law, joint marketing partners or resellers may share information about you with us so that we can better understand which of our Services may be of interest to you.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-top:5.0000pt;margin-bottom:0.0000pt;margin-left:18.7500pt;
mso-margin-top-alt:auto;text-indent:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);mso-list:l3 level1 lfo4;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Advertising Networks &amp; Analytics Providers</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">: We work with these providers to provide us with de-identified information about how you found our Sites and how you interact with the Sites and Services. This information may be collected prior to account creation - for more information on how you can manage collection of this data, please see our</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
color:rgb(5,15,25);font-size:10.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">Cookie Policy</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
color:rgb(5,15,25);font-size:10.0000pt;">.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
color:rgb(5,15,25);font-size:10.0000pt;"><o:p></o:p></span></p><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">HOW YOUR PERSONAL INFORMATION IS USED</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><p class="MsoNormal"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">Our primary purpose in collecting personal information is to provide you with a secure, smooth, efficient, and customized experience. We generally use personal information to create, develop, operate, deliver, and improve our Services, content and advertising; and for loss prevention and anti-fraud purposes. We may use this information in the following ways:</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">1)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To maintain legal and regulatory compliance</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">Most of our core Services are subject to laws and regulations requiring us to collect, use, and store your personal information in certain ways. For example, Vision-X must identify and verify customers using our Services in order to comply with anti-money laundering laws across jurisdictions. This includes collection and storage of your photo identification. In addition, we use third parties to verify your identity by comparing the personal information you provide against third-party databases and public records. When you seek to link a bank account to your Vision-X Account, we may require you to provide additional information which we may use in collaboration with service providers acting on our behalf to verify your identity or address, and/or to manage risk as required under applicable law. If you do not provide personal information required by law, we will have to close your account.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">2)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To enforce our terms in our user agreement and other agreements</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">Vision-X handles sensitive information, such as your identification and financial data, so it is very important for us and our customers that we actively monitor, investigate, prevent, and mitigate any potentially prohibited or illegal activities, enforce our agreements with third parties, and/or prevent and detect violations of our posted user agreement or agreements for other Services. In addition, we may need to collect fees based on your use of our Services. We collect information about your account usage and closely monitor your interactions with our Services. We may use any of your personal information collected for these purposes. The consequences of not processing your personal information for such purposes is the termination of your account.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">3)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To detect and prevent fraud and/or funds loss</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We process your personal information in order to help detect, prevent, and mitigate fraud and abuse of our services and to protect you against account compromise or funds loss.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">4)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To provide Vision-X's Services</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We process your personal information to provide the Services to you. For example, when you want to store funds on our platform, we require certain information such as your identification, contact information, and payment information. We cannot provide you with Services without such information. Third parties such as identity verification services may also access and/or collect your personal information when providing identity verification and/or fraud prevention services.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">5)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To provide Service communications</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We send administrative or account-related information to you to keep you updated about our Services, inform you of relevant security issues or updates, or provide other transaction-related information. Without such communications, you may not be aware of important developments relating to your account that may affect how you can use our Services. You may not opt-out of receiving critical service communications, such as emails or mobile notifications sent for legal or security purposes. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">6)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To provide customer service</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We process your personal information when you contact us to resolve any questions, disputes, collect fees, or to troubleshoot problems. Without processing your personal information for such purposes, we cannot respond to your requests and ensure your uninterrupted use of the Services.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">7)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To ensure quality control</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We process your personal information for quality control and staff training to make sure we continue to provide you with accurate information. If we do not process personal information for quality control purposes, you may experience issues on the Services such as inaccurate transaction records or other interruptions.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">8)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To ensure network and information security</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We process your personal information in order to enhance security, monitor and verify identity or service access, combat spam or other malware or security risks and to comply with applicable security laws and regulations. The threat landscape on the internet is constantly evolving, which makes it more important than ever that we have accurate and up-to-date information about your use of our Services. Without processing your personal information, we may not be able to ensure the security of our Services.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">9)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">For research and development purposes</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We process your personal information to better understand the way you use and interact with Vision-X's Services. In addition, we use such information to customize, measure, and improve Vision-X's Services and the content and layout of our website and applications, and to develop new services. Without such processing, we cannot ensure your continued enjoyment of our Services.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">10)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To enhance your experience</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We process your personal information to provide a personalized experience, and implement the preferences you request. For example, you may choose to provide us with access to certain personal information stored by third parties. Without such processing, we may not be able to ensure your continued enjoyment of part or all of our Services.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">11)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To facilitate corporate acquisitions, mergers, or transactions</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We may process any information regarding your account and use of our Services as is necessary in the context of corporate acquisitions, mergers, or other corporate transactions. You have the option of closing your account if you do not wish to have your personal information processed for such purposes. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">12)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">To engage in marketing activities</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">Based on your communication preferences, we may send you marketing communications (e.g. emails or mobile notifications) to inform you about our events or our partner events; to deliver targeted marketing; and to provide you with promotional offers. Our marketing will be conducted in accordance with your advertising marketing preferences and as permitted by applicable law.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">13)&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">For any purpose</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We may disclose your personal information for any purpose you consent to.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);">We will not use your personal information for purposes other than those purposes we have disclosed to you, without your permission. From time to time, and as required under the applicable law, we may request your permission to allow us to share your personal information with third parties. You may opt out of having your personal information shared with third parties, or allowing us to use your personal information for any purpose that is incompatible with the purposes for which we originally collected it or subsequently obtained your authorization. If you choose to so limit the use of your personal information, certain features or Vision-X Services may not be available to you. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);"><o:p></o:p></span></p><h1 align="justify" style="text-align:justify;text-justify:inter-ideograph;"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">MARKETING </span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(54,96,145);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><h1 align="justify" style="text-align:justify;text-justify:inter-ideograph;"><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;font-weight:bold;
font-size:10.0000pt;">Direct Marketing</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;">:</span><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:bold;font-size:10.0000pt;">&nbsp;</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;">Direct marketing includes any communications to you that are only based on advertising or promoting our products and services. We will only contact you by electronic means (email or SMS) based on our legitimate interests, as permitted by applicable law, or your consent</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(54,96,145);font-weight:normal;font-size:10.0000pt;">. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;">If you are a new customer, we will contact you by electronic means for marketing purposes only if you have consented to such communication. If you do not want us to send you marketing communications, please go to your account settings to opt-out or submit a request via our&nbsp;</span><span><a href=" "><u><span class="18" style="mso-spacerun:'yes';font-family:Arial;color:rgb(0,32,96);
font-weight:normal;text-decoration:underline;text-underline:single;
font-size:10.0000pt;">Support Portal</span></u></a></span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,32,96);font-weight:normal;font-size:10.0000pt;">.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;">&nbsp;You may raise such objection with regard to initial or further processing for purposes of direct marketing, at any time and free of charge. Direct marketing includes any communications to you that are only based on advertising or promoting our products and services. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;"><o:p></o:p></span></h1><h1 align="justify" style="text-align:justify;text-justify:inter-ideograph;"><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;font-weight:bold;
font-size:10.0000pt;">Third Party Marketing</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;">: We will obtain your express consent before we share your personal information with any third parties for marketing purposes.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(54,96,145);font-weight:normal;font-size:10.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(54,96,145);font-weight:normal;font-size:10.0000pt;"><o:p></o:p></span></h1><h1 align="justify" style="text-align:justify;text-justify:inter-ideograph;"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">WHY WE SHARE PERSONAL INFORMATION WITH OTHER PARTIES</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><p class="MsoNormal"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:12.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We take care to allow your personal information to be accessed only by those who require access to perform their tasks and duties, and to share only with third parties who have a legitimate purpose for accessing it.&nbsp;</span><b><span class="17" style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
line-height:114%;font-weight:bold;font-size:10.0000pt;">Vision-X will never sell or rent your personal information to third parties without your explicit consent</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">. The categories of persons with whom we may share Personal Data include:</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Service providers and/or data processors:&nbsp;</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">We may share Personal Data with third-party service providers that perform services and functions at our direction and on our behalf. These third-party service providers may, for example, provide you with Services, verify your identity, assist in processing transactions, send you advertisements for our products and Services, or provide customer support.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-weight:bold;font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-weight:bold;font-size:10.0000pt;">Other parties to transactions, such as sellers:&nbsp;</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">We may share information with the other participants to your transactions, including other users from whom you are purchasing the digital asset.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">Financial institutions and other companies involved in helping you make payments in connection with transactions</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">Affiliates that receive referrals from our Website</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Symbol;mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">Other third-parties for our business purposes or as permitted or required by law, including:</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level2 lfo5;"><!--[if !supportLists]--><span style="font-family:'Courier New';mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">o<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">To comply with any legal, regulatory or contractual obligation, or with any legal or regulatory process (such as a valid court order or subpoena);</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level2 lfo5;"><!--[if !supportLists]--><span style="font-family:'Courier New';mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">o<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">To establish, exercise, or defend legal claims;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level2 lfo5;"><!--[if !supportLists]--><span style="font-family:'Courier New';mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">o<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">In response to a request by a government agency, such as law enforcement authorities or a judicial order;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level2 lfo5;"><!--[if !supportLists]--><span style="font-family:'Courier New';mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">o<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">To enforce our Website Terms of Service or our internal policies;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level2 lfo5;"><!--[if !supportLists]--><span style="font-family:'Courier New';mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">o<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">To prevent physical harm or financial loss, in connection with an investigation of suspected or actual illegal activity, or to otherwise protect our or others’ rights, property, or safety;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level2 lfo5;"><!--[if !supportLists]--><span style="font-family:'Courier New';mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">o<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">To facilitate a purchase or sale of all or part of Vision-X's business. For example, by sharing data with a company we plan to merge with or be acquired by; or</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:18.0000pt;text-indent:-18.0000pt;
text-align:justify;text-justify:inter-ideograph;background:rgb(255,255,255);
mso-list:l2 level2 lfo5;"><!--[if !supportLists]--><span style="font-family:'Courier New';mso-fareast-font-family:'Times New Roman';mso-bidi-font-family:Arial;
font-size:10.0000pt;"><span style="mso-list:Ignore;">o<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;">To support our audit, compliance, and corporate governance functions. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p></o:p></span></p><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">INTERNATIONAL TRANSFERS OF DATA</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><p class="MsoNormal"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:12.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">Please note that we may transfer Personal Data we collect about you to countries other than the country in which the information was originally collected. Those countries may not have the same data protection laws as the country in which you initially provided the information. When we transfer your Personal Data to other countries, we take steps designed to ensure that the transfer is in accordance with applicable law. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);">Data gathered in the European Economic Area (EEA) may be transferred to, stored and processed at a destination(s) outside of the EEA. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);"><o:p></o:p></span></p><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;
background:rgb(255,255,255);mso-shading:rgb(255,255,255);">SPECIAL PROVISION FOR VISION-X ATM (VERVE CARD) USERS </span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;
background:rgb(255,255,255);mso-shading:rgb(255,255,255);"><o:p></o:p></span></b></h1><p class="MsoNormal"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:Calibri;
font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">In order to provide the Vision-X ATM Card Service to you, we have partnered with Rubies Microfinance Bank Limited (collectively “Rubies”). Rubies is the issuer of the Vision-X Card and is a member of the Verve card scheme, of which will be used to enable your Vision-X Card to operate as a normal debit card. When you sign up and obtain a Vision-X Card, you agree to Rubies own terms and conditions and Privacy Policy and as a result Rubies will be an independent data controller in relation to the personal information they collect and hold relating to you.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">We may at times need to share some of your personal information that we control with Rubies to enable us and Rubies provide you with the Vision-X Card Service. Where we do this, Rubies will act as a data processor and only process your personal information to the extent necessary to enable us and Rubies to provide the Vision-X Card Service to you. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">DATA SECURITY</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);">&nbsp;</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;"><o:p></o:p></span></b></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);">Vision-X has implemented safeguards designed to protect your Personal Data, including measures designed to prevent Personal Data against loss, misuse, and unauthorized access and disclosure.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">However, we cannot guarantee that loss, misuse, unauthorized acquisition, or alteration of your data will not occur. Please recognize that you play a vital role in protecting your own personal information. When registering with our Services, it is important to choose a password of sufficient length and complexity, to not reveal this password to any third-parties, and to immediately notify us if you become aware of any unauthorized access to or use of your account.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">Furthermore, we cannot ensure or warrant the security or confidentiality of information you transmit to us or receive from us by Internet or wireless connection, including email, phone, or SMS, since we have no way of protecting that information once it leaves and until it reaches us. If you have reason to believe that your data is no longer secure, please contact us using the contact information provided in this Privacy Policy. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">RETENTION OF PERSONAL INFORMATION</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-size:10.0000pt;"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;
background:rgb(255,255,255);mso-shading:rgb(255,255,255);">We store your personal information securely throughout the life of your CB Account. We will only retain your personal information for as long as necessary to fulfill the purposes for which we collected it, including for the purposes of satisfying any legal, accounting, or reporting obligations or to resolve disputes.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(5,15,25);font-size:10.0000pt;
background:rgb(255,255,255);mso-shading:rgb(255,255,255);"><o:p></o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);">CHILDREN </span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);"><o:p></o:p></span></b></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);">Children under the age of 18 are not permitted to register or use the APP or any functionality contained on it. If we learn that we have collected information, including Personal Data, from an individual under 18 years of age without parental consent, we will delete that information immediately. </span><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(54,96,145);font-weight:bold;
font-size:10.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);"><o:p></o:p></span></b></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;">OUR WEB COOKIE POLICY </span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(0,0,255);font-weight:bold;
font-size:10.0000pt;"><o:p></o:p></span></b></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">A web cookie is a small piece of data sent from a website and stored on your computer by your web browser while you browse. To make your experience on our site more convenient, we use web cookies for our sites. The type of data captured by our web cookies is non-personal data such as site traffic behaviour.</span><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-weight:bold;font-size:10.0000pt;">&nbsp;</span></b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">If you don't wish to accept a web cookie from us, you're able to configure your web browser to decline the web cookie that is being sent. However, declining web cookies may result in some of our services not functioning as intended.</span><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-weight:bold;font-size:10.0000pt;">&nbsp;</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;color:rgb(54,96,145);font-weight:bold;
font-size:10.0000pt;"><o:p></o:p></span></b></p><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(54,96,145);font-weight:bold;font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></b></h1><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">YOUR PRIVACY RIGHTS</span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:0.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:0.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">You have the right to access your personal data held by Vision-X, by contacting us with a request at&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-weight:normal;font-size:10.0000pt;
background:rgb(255,255,255);mso-shading:rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:114%;font-weight:normal;
font-size:10.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);"><a href="mailto:support@visionxcrypto.com">support@visionxcrypto.com</a></span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">. For your protection, we will take steps to verify your identity before fulfilling your request. If there are any changes to your personal information or if you believe that the information we have about you is inaccurate, incomplete, misleading or not up-to-date, you must inform us accordingly at&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-weight:normal;font-size:10.0000pt;
background:rgb(255,255,255);mso-shading:rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:114%;font-weight:normal;
font-size:10.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);"><a href="mailto:support@visionxcrypto.com">support@visionxcrypto.com</a></span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;">. We may use our discretion in allowing correction requests and may request further documentary evidence of any new information in order to avoid fraud and inaccuracy.</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p></o:p></span></p><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">APP ACCESS </span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><h1><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);">In order to access the APP and all its features, you must register and activate a Vision-X Wallet, which will provide you with full access to the APP. </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);"><o:p></o:p></span></h1><h1><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;">HOW TO CONTACT US </span></b><b><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
color:rgb(0,0,255);font-weight:bold;font-size:10.0000pt;"><o:p></o:p></span></b></h1><h1><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);">We welcome your views about the APP and our privacy policy. If you would like to contact us with any enquiries or comments, please send an email to </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
mso-bidi-font-family:'Times New Roman';font-weight:normal;font-size:10.0000pt;
background:rgb(255,255,255);mso-shading:rgb(255,255,255);"><a href="mailto:support@visionxcrypto.com">support@visionxcrypto.com</a></span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:SimSun;
font-weight:normal;font-size:10.0000pt;background:rgb(255,255,255);
mso-shading:rgb(255,255,255);"><o:p></o:p></span></h1><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:-18.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal" align="justify" style="margin-bottom:6.0000pt;margin-left:36.0000pt;text-align:justify;
text-justify:inter-ideograph;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:12.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="p" align="justify" style="margin-top:0.0000pt;margin-bottom:18.0000pt;text-align:justify;
text-justify:inter-ideograph;line-height:114%;background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:'Times New Roman';
line-height:114%;font-size:10.0000pt;"><o:p>&nbsp;</o:p></span></p></div>
			
			
			
                </div>
              </div>
            </div>

          
          </div>
        </section>
        <!-- End. about_cc_grid -->

       


@endsection


